version: '3.8'

services:
  # Next.js Application
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=mongodb+srv://louiscyrano:Figoro21@cluster0.1yh3agm.mongodb.net/my-project?retryWrites=true&w=majority&appName=Cluster0
      - MONGODB_URI=mongodb+srv://louiscyrano:Figoro21@cluster0.1yh3agm.mongodb.net/my-project?retryWrites=true&w=majority&appName=Cluster0
      - NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_SECRET=dev-secret-key
    volumes:
      - .:/app
      - /app/node_modules
      - ./data:/app/data
    command: npm run dev

  # Redis for development
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data: